// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB77yxNJEFwDW59LxMpbJbM2Bzm3btGqXU',
    appId: '1:455996065105:web:4e331329f568b06184ff70',
    messagingSenderId: '455996065105',
    projectId: 'sagatrans-6c20c',
    authDomain: 'sagatrans-6c20c.firebaseapp.com',
    storageBucket: 'sagatrans-6c20c.appspot.com',
    measurementId: 'G-17RK18BSML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiGs5fwGy2Oj55y0QQG1p5dPreZlDVJ9k',
    appId: '1:455996065105:android:b1e204a290f7f48384ff70',
    messagingSenderId: '455996065105',
    projectId: 'sagatrans-6c20c',
    storageBucket: 'sagatrans-6c20c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj0IO7OHuuQKFwTP5NBmMA52Ys2cp5QuE',
    appId: '1:455996065105:ios:85e51818bf28b18c84ff70',
    messagingSenderId: '455996065105',
    projectId: 'sagatrans-6c20c',
    storageBucket: 'sagatrans-6c20c.appspot.com',
    iosBundleId: 'com.example.sistemManagemenTiketBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj0IO7OHuuQKFwTP5NBmMA52Ys2cp5QuE',
    appId: '1:455996065105:ios:85e51818bf28b18c84ff70',
    messagingSenderId: '455996065105',
    projectId: 'sagatrans-6c20c',
    storageBucket: 'sagatrans-6c20c.appspot.com',
    iosBundleId: 'com.example.sistemManagemenTiketBus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB77yxNJEFwDW59LxMpbJbM2Bzm3btGqXU',
    appId: '1:455996065105:web:ca2832aa09033c8284ff70',
    messagingSenderId: '455996065105',
    projectId: 'sagatrans-6c20c',
    authDomain: 'sagatrans-6c20c.firebaseapp.com',
    storageBucket: 'sagatrans-6c20c.appspot.com',
    measurementId: 'G-MNKZLDLVJT',
  );
}
